spring.application.name=drukconnect
server.port=8080
server.forward-headers-strategy=framework

spring.datasource.url=jdbc:mysql://localhost:3306/druk_connect?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Thecap999@

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=forbusinesssjy999@gmail.com
spring.mail.password=zgpuzffwgnuuihtr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.auth.send-email-otp=true
app.auth.require-email-otp=true
app.auth.current-guideline-version=1.0

app.jwt.issuer=drukconnect
app.jwt.access-ttl=15m
app.jwt.refresh-ttl=7d
app.jwt.secret-base64=NJK77UMjKOXT9n761ok56eDQjmTGHqSBA1li+J81GTY=

app.otp.ttl=5m
app.otp.resend-cooldown=60s
app.otp.max-attempts=5
app.otp.digits=4
app.otp.hmac-secret-base64=eyvzetIbGshD3m0V1M6tj8TzqqtmQ8xqdzghLtPbLII=

app.mail.enabled=true
app.mail.from=forbusinesssjy999@gmail.com

# =========================================================
# SPRINGDOC / SWAGGER
# =========================================================

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none

springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.persist-authorization=false
springdoc.swagger-ui.filter=true



# =========================================================
# DRUKCONNECT AUTH
# =========================================================

app.auth.send-phone-otp=false
app.auth.require-phone-otp=false

spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR


# =========================================================
# SMS - TEXTBELT
# =========================================================
app.sms.enabled=true
app.sms.endpoint=https://textbelt.com/text
app.sms.api-key=textbelt
app.sms.sender-id=DrukConnect

app.vouch.invitation-url=http://localhost:4200/vouch-invitation
app.vouch.invitation-ttl=7d

app.vouch.backend-url=http://localhost:8080
app.vouch.response-token-ttl=7d